### ISSUE TITLE
Signature Error when sending orders

### ISSUE THREAD

**Issue by olahoppy1** [xt-com/xt4-python-demo#2]
Hi 

I tried integrating myself, I could get all the public and private endpoints to work with the new AUTH method but was getting AUTH_103 error when creating order. 

I noticed the python SDK was released, tried that, and I still get the AUTH_103 error, even when copy and pasting the example from the README file. Not sure if there is something wrong with the request or if the backend is returning the wrong error code and it's a missing field? 

Any ideas? 

Thanks

**Comment by olahoppy1** [comment]
Was an issue with my BASE URL, had http: instead of https: 


Closing issue

**Comment by wiloyee** [comment]
switching from http: to https: didn't solve the issue for me
